CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    real_name VARCHAR(50),
    phone VARCHAR(20),
    email VARCHAR(100),
    status INT DEFAULT 1,
    role VARCHAR(20) DEFAULT 'nurse',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS elder_health_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    gender VARCHAR(2),
    birth_date DATE,
    id_card VARCHAR(18),
    phone VARCHAR(20),
    address VARCHAR(200),
    emergency_contact VARCHAR(50),
    emergency_phone VARCHAR(20),
    medical_history TEXT,
    family_history TEXT,
    cognitive_baseline TEXT,
    risk_level VARCHAR(20),
    status INT DEFAULT 1,
    create_by BIGINT,
    update_by BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cognitive_assessment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    elder_id BIGINT NOT NULL,
    assessment_type VARCHAR(50),
    total_score INT,
    risk_level VARCHAR(20),
    assessment_result TEXT,
    recommendations TEXT,
    assessor VARCHAR(50),
    assessment_place VARCHAR(100),
    assessment_time TIMESTAMP,
    next_assessment_date DATE,
    remark VARCHAR(500),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS intervention_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    elder_id BIGINT NOT NULL,
    plan_name VARCHAR(100),
    plan_type VARCHAR(50),
    risk_level VARCHAR(20),
    cognitive_training TEXT,
    lifestyle_intervention TEXT,
    rehabilitation_plan TEXT,
    goals TEXT,
    start_date DATE,
    end_date DATE,
    responsible_doctor VARCHAR(50),
    status VARCHAR(20) DEFAULT 'pending',
    remark VARCHAR(500),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS intervention_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    elder_id BIGINT NOT NULL,
    execution_type VARCHAR(50),
    content TEXT,
    execution_date DATE,
    duration INT,
    effect_evaluation VARCHAR(20),
    evaluator VARCHAR(50),
    remark VARCHAR(500),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_dict (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_type VARCHAR(50),
    dict_key VARCHAR(100),
    dict_value VARCHAR(200),
    sort INT DEFAULT 0,
    remark VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS risk_warning (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    elder_id BIGINT NOT NULL,
    risk_level VARCHAR(20),
    warning_type VARCHAR(50),
    warning_msg TEXT,
    is_read INT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
